### PR TITLE
Start adding MLlib example and try to fix build issue

### PR DESCRIPTION
**Pull request by holdenk**
Start adding MLlib example and try to fix build issue in travis.

### CODE REVIEW

**Comment by rachelwarren** [comment]
hmmm still failing

**Comment by holdenk** [comment]
Yay it passes! :)

**Comment by holdenk** [comment]
Although I do decrease code coverage - but I'll merge to fix the build.

**Comment by rachelwarren** [comment]
YAy. Times like this I wish git had
Emoji integration.

**Pull request merged**
